# Generated by Django 2.0.3 on 2018-06-26 12:41

from django.db import migrations
import users.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.manager.CustomUserManager()),
            ],
        ),
    ]
