# Generated by Django 2.0.3 on 2018-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180626_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country_code',
            field=models.CharField(max_length=15),
        ),
    ]
