# Generated by Django 2.0.4 on 2018-08-01 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_remove_member_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='tax_number',
        ),
    ]
