# Generated by Django 2.0.3 on 2018-06-27 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180626_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('next_code', models.UUIDField(blank=True, default=None, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('one_off', models.BooleanField(default=True)),
            ],
        ),
    ]
