# Generated by Django 2.0.3 on 2018-06-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invitelink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InviteLink',
            new_name='InviteCode',
        ),
    ]
