# Generated by Django 2.0.3 on 2018-06-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_invitecode_used_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitecode',
            name='next_code',
        ),
    ]
