# Generated by Django 2.0.3 on 2018-06-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_invitecode_next_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
