# Generated by Django 2.0.3 on 2018-06-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='sort',
            new_name='index',
        ),
    ]
