# Generated by Django 2.0.3 on 2018-06-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_auto_20180613_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateaction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='candidateaction',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='CandidateAction',
        ),
    ]
