# Generated by Django 2.0.3 on 2018-07-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_auto_20180613_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('index',)},
        ),
        migrations.RenameField(
            model_name='action',
            old_name='type',
            new_name='action_type',
        ),
        migrations.RenameField(
            model_name='actiontype',
            old_name='fee',
            new_name='must_fee',
        ),
        migrations.AddField(
            model_name='action',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='must_approvable',
            field=models.BooleanField(default=False),
        ),
    ]
