# Generated by Django 2.0.4 on 2018-07-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_auto_20180703_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='to_delete',
            field=models.BooleanField(default=False),
        ),
    ]
