# Generated by Django 2.0.4 on 2018-07-30 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member_profile', '0001_initial'),
        ('jobboard', '0002_auto_20180730_1320'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialisations',
            field=models.ManyToManyField(blank=True, to='jobboard.Specialisation'),
        ),
        migrations.AddField(
            model_name='position',
            name='busyness',
            field=models.ManyToManyField(to='member_profile.Busyness'),
        ),
        migrations.AddField(
            model_name='position',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='member_profile.Profile'),
        ),
        migrations.AddField(
            model_name='position',
            name='schedule',
            field=models.ManyToManyField(to='member_profile.Schedule'),
        ),
        migrations.AddField(
            model_name='languageitem',
            name='language',
            field=models.ForeignKey(on_delete='name', related_name='items', to='member_profile.Language'),
        ),
        migrations.AddField(
            model_name='languageitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='member_profile.Profile'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='member_profile.Profile'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member_profile.EducationLevel'),
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='member_profile.Profile'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_profile.Country'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizenship', to='member_profile.Profile'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='member_profile.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='languageitem',
            unique_together={('language', 'profile')},
        ),
    ]
