# Generated by Django 2.0.3 on 2018-08-06 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('member_profile', '0002_auto_20180730_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(
                    choices=[('COURSE', 'Course'), ('TRAINING', 'Training'), ('CONFERENCE', 'Conference')],
                    max_length=20)),
                ('institute', models.CharField(blank=True, max_length=127, null=True)),
                ('profession', models.CharField(blank=True, max_length=127, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('has_certificate', models.BooleanField(default=False)),
                ('profile',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_education',
                                   to='member_profile.Profile')),
            ],
        ),
    ]
