# Generated by Django 2.0.3 on 2018-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('member_profile', '0003_additionaleducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
