# Generated by Django 2.0.2 on 2018-03-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancy', '0014_auto_20180312_0823'),
        ('jobboard', '0033_auto_20180301_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVacancyPassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passed', models.NullBooleanField(default=None)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='candidatevacancypassing',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.VacancyTest'),
        ),
    ]
