# Generated by Django 2.0.4 on 2018-07-30 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('quiz', '0001_initial'),
        ('pipeline', '0002_auto_20180730_1320'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exampassed',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exampassed',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.ActionExam'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_categories', to='company.Company'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='quiz.Category'),
        ),
        migrations.AddField(
            model_name='answerforverification',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='answerforverification',
            name='related_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='actionexam',
            name='action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='pipeline.Action'),
        ),
        migrations.AddField(
            model_name='actionexam',
            name='questions',
            field=models.ManyToManyField(to='quiz.Question'),
        ),
    ]
