# Generated by Django 2.0.3 on 2018-04-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('passing_grade', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(default=0)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='pipeline.Action')),
                ('questions', models.ManyToManyField(to='quiz.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancyexam',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='vacancyexam',
            name='vacancy',
        ),
        migrations.AlterField(
            model_name='exampassing',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.ActionExam'),
        ),
        migrations.DeleteModel(
            name='VacancyExam',
        ),
    ]
