# Generated by Django 2.0.3 on 2018-06-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exampassed',
            old_name='cv',
            new_name='profile',
        ),
    ]
