# Generated by Django 2.0.3 on 2018-08-03 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('quiz', '0002_auto_20180730_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
