# Generated by Django 2.0.3 on 2018-07-03 06:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
        ('quiz', '0002_auto_20180614_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampassed',
            name='profile',
        ),
        migrations.AddField(
            model_name='exampassed',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='jobboard.Candidate'),
        ),
        migrations.AlterField(
            model_name='actionexam',
            name='action',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='pipeline.Action'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='weight',
            field=models.SmallIntegerField(default=1, help_text='Value from -100 to 100', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
