# Generated by Django 2.0.3 on 2018-04-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_curriculumvitae_enabled'),
        ('quiz', '0003_auto_20180405_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampassing',
            name='candidate',
        ),
        migrations.AddField(
            model_name='exampassing',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='cv.CurriculumVitae'),
        ),
    ]
