# Generated by Django 2.0.4 on 2018-07-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180703_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='jobboard.Employer'),
        ),
    ]
