# Generated by Django 2.0.3 on 2018-04-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_curriculumvitae_enabled'),
        ('quiz', '0004_auto_20180409_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamPassing',
            new_name='ExamPassed',
        ),
    ]
