# Generated by Django 2.0.2 on 2018-03-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0033_auto_20180301_1146'),
        ('quiz', '0005_auto_20180312_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobboard.Employer'),
        ),
    ]
