# Generated by Django 2.0.2 on 2018-03-12 19:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180312_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancytest',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='vacancytest',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='vacancytest',
            name='question',
        ),
        migrations.RemoveField(
            model_name='vacancytest',
            name='title',
        ),
        migrations.AddField(
            model_name='vacancytest',
            name='fidelity_percent',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancytest',
            name='questions',
            field=models.ManyToManyField(to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='vacancytest',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='vacancy.Vacancy'),
        ),
    ]
