# Generated by Django 2.0.2 on 2018-03-13 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20180312_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vacancytest',
            name='fidelity_percent',
            field=models.SmallIntegerField(default=9, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
