# Generated by Django 2.0.2 on 2018-03-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20180313_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='weight',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='coordinate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.SmallIntegerField(default=1),
        ),
    ]
