# Generated by Django 2.0.2 on 2018-03-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20180313_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='coordinate',
        ),
    ]
