# Generated by Django 2.0.2 on 2018-03-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_question_coordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('template_name', models.CharField(help_text='*_question.html', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='kind',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.QuestionKind'),
        ),
    ]
