# Generated by Django 2.0.2 on 2018-03-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20180314_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionkind',
            name='changeable',
            field=models.BooleanField(default=False),
        ),
    ]
