# Generated by Django 2.0.2 on 2018-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_questionkind_changeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionkind',
            name='min_answers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
