# Generated by Django 2.0.2 on 2018-03-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_questionkind_min_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyexam',
            name='fidelity_percent',
        ),
        migrations.AddField(
            model_name='vacancyexam',
            name='passing_grade',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
