# Generated by Django 2.0.2 on 2018-03-15 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20180315_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionkind',
            old_name='changeable',
            new_name='w2v',
        ),
        migrations.AlterField(
            model_name='vacancyexam',
            name='passing_grade',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
