# Generated by Django 2.0.2 on 2018-03-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20180315_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampassing',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
