# Generated by Django 2.0.2 on 2018-03-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_exampassing_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exampassing',
            old_name='test',
            new_name='exam',
        ),
    ]
