# Generated by Django 2.0.2 on 2018-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20180315_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampassing',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
