# Generated by Django 2.0.2 on 2018-03-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20180315_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampassing',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='jobboard.Candidate'),
        ),
    ]
