# Generated by Django 2.0.2 on 2018-03-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20180316_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerForVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('points', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='quiz.Question')),
            ],
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('?',)},
        ),
        migrations.AddField(
            model_name='answerforverification',
            name='related_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Answer'),
        ),
    ]
