# Generated by Django 2.0.2 on 2018-03-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_auto_20180318_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerforverification',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
