# Generated by Django 2.0.2 on 2018-03-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_answerforverification_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyexam',
            name='max_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
