# Generated by Django 2.0.2 on 2018-03-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20180319_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionkind',
            name='one_right_answer',
            field=models.BooleanField(default=True),
        ),
    ]
