# Generated by Django 2.0.4 on 2018-07-30 10:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jobboard.helpers
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Date from you want to interview candidates')),
                ('end_date', models.DateField(blank=True, help_text='Date to you want to interview candidates', null=True)),
                ('start_time', models.TimeField(default=django.utils.timezone.now, help_text='Time from you want to interview')),
                ('end_time', models.TimeField(blank=True, default='18:00', help_text='Time to you want to interview', null=True)),
                ('duration', models.IntegerField(default=10, help_text='Interview duration', validators=[django.core.validators.MinValueValidator(5, 'Interview duration cannot be less than 5 minutes')])),
            ],
            options={
                'abstract': False,
            },
            bases=(jobboard.helpers.BaseAction, models.Model),
        ),
        migrations.CreateModel(
            name='InterviewPassed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.CharField(max_length=32)),
                ('conf_id', models.CharField(max_length=32)),
                ('link_start', models.URLField(max_length=768)),
                ('link_join', models.URLField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('action_interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to='interview.ActionInterview')),
            ],
        ),
    ]
