# Generated by Django 2.0.3 on 2018-06-27 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jobboard.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='pipeline.Action')),
            ],
            options={
                'abstract': False,
            },
            bases=(jobboard.helpers.BaseAction, models.Model),
        ),
    ]
