# Generated by Django 2.0.3 on 2018-06-27 15:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioninterview',
            name='duration',
            field=models.IntegerField(default=10, help_text='Interview duration', validators=[django.core.validators.MinValueValidator(5, 'Interview duration cannot be less than 5 minutes')]),
        ),
        migrations.AlterField(
            model_name='actioninterview',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date to you want to interview candidates', null=True),
        ),
        migrations.AlterField(
            model_name='actioninterview',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Time to you want to interview', null=True),
        ),
        migrations.AlterField(
            model_name='actioninterview',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date from you want to interview candidates'),
        ),
        migrations.AlterField(
            model_name='actioninterview',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time from you want to interview'),
        ),
    ]
