# Generated by Django 2.0.3 on 2018-06-28 08:22

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
        ('interview', '0002_auto_20180627_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPassed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('action_interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to='interview.ActionInterview')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to='jobboard.Candidate')),
            ],
        ),
        migrations.AddField(
            model_name='meetingpassed',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='interview.ScheduledMeeting'),
        ),
    ]
