# Generated by Django 2.0.3 on 2018-08-03 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0002_auto_20180730_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioninterview',
            name='recruiters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
