# Generated by Django 2.0.3 on 2018-06-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20180628_0822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingPassed',
            new_name='InterviewPassed',
        ),
    ]
