# Generated by Django 2.0.3 on 2018-08-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interview', '0003_actioninterview_recruiters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioninterview',
            name='start_time',
            field=models.TimeField(default='08:00', help_text='Time from you want to interview'),
        ),
    ]
