# Generated by Django 2.0.3 on 2018-06-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20180628_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewpassed',
            old_name='meeting',
            new_name='interview',
        ),
    ]
