# Generated by Django 2.0.3 on 2018-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20180411_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
