# Generated by Django 2.0.3 on 2018-08-09 07:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0004_auto_20180803_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioninterview',
            name='duration',
            field=models.IntegerField(default=10, help_text='Interview duration', validators=[
                django.core.validators.MinValueValidator(10, 'Interview duration cannot be less than 10 minutes')]),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledmeeting',
            unique_together={('action_interview', 'candidate', 'is_removed')},
        ),
    ]
