# Generated by Django 2.0.3 on 2018-04-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_auto_20180411_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewpassed',
            name='interview',
        ),
        migrations.DeleteModel(
            name='InterviewPassed',
        ),
    ]
