# Generated by Django 2.0.3 on 2018-06-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_auto_20180628_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioninterview',
            name='end_time',
            field=models.TimeField(blank=True, default='18:00', help_text='Time to you want to interview', null=True),
        ),
    ]
