# Generated by Django 2.0.3 on 2018-06-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_auto_20180628_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeeting',
            name='link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
