# Generated by Django 2.0.3 on 2018-06-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_scheduledmeeting_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledmeeting',
            old_name='link',
            new_name='link_join',
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='conf_id',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='link_start',
            field=models.URLField(default='http://ya.ru'),
            preserve_default=False,
        ),
    ]
