# Generated by Django 2.0.4 on 2018-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_auto_20180629_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='link_start',
            field=models.URLField(max_length=768),
        ),
    ]
