# Generated by Django 2.0.4 on 2018-07-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_auto_20180629_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeeting',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
