# Generated by Django 2.0.4 on 2018-07-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_scheduledmeeting_is_removed'),
        ('interview', '0012_auto_20180705_1237'),
    ]

    operations = [
    ]
