# Generated by Django 2.0 on 2018-02-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobboard', '0030_auto_20180208_0654'),
        ('cv', '0027_auto_20180208_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVacancyPassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passed', models.NullBooleanField(default=None)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CVOnVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.CurriculumVitae')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('interview_fee', models.CharField(default=0, max_length=31)),
                ('allowed_amount', models.CharField(default=0, max_length=31)),
                ('salary_from', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('salary_up_to', models.PositiveIntegerField(blank=True, null=True)),
                ('enabled', models.NullBooleanField(default=True)),
                ('busyness', models.ManyToManyField(blank=True, to='cv.Busyness')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.Employer')),
                ('keywords', models.ManyToManyField(blank=True, to='jobboard.Keyword')),
                ('schedule', models.ManyToManyField(blank=True, to='cv.Schedule')),
                ('specializations', models.ManyToManyField(blank=True, to='jobboard.Specialisation')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='cvonvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Vacancy'),
        ),
        migrations.AddField(
            model_name='candidatevacancypassing',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.VacancyTest'),
        ),
    ]
