# Generated by Django 2.0.3 on 2018-03-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobboard', '0001_initial'),
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVOnVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.CurriculumVitae')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('experience', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirement', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=255)),
                ('salary_from', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('salary_up_to', models.PositiveIntegerField(blank=True, null=True)),
                ('enabled', models.NullBooleanField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('busyness', models.ManyToManyField(blank=True, to='cv.Busyness')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='jobboard.Employer')),
                ('keywords', models.ManyToManyField(blank=True, to='jobboard.Keyword')),
                ('schedule', models.ManyToManyField(blank=True, to='cv.Schedule')),
                ('specialisations', models.ManyToManyField(blank=True, to='jobboard.Specialisation')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VacancyOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='cv.CurriculumVitae')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='cvonvacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Vacancy'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancyoffer',
            unique_together={('vacancy', 'cv')},
        ),
    ]
