# Generated by Django 2.0.3 on 2018-06-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidateprofile', '0008_remove_candidateprofile_published'),
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancyoffer',
            old_name='cv',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='vacancyoffer',
            unique_together={('vacancy', 'profile')},
        ),
    ]
