# Generated by Django 2.0.3 on 2018-06-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidateprofile', '0008_remove_candidateprofile_published'),
        ('vacancy', '0002_auto_20180614_0616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVOnVacancy',
            new_name='ProfileOnVacancy',
        ),
    ]
