# Generated by Django 2.0.3 on 2018-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='allowed_amount',
            field=models.CharField(default=0, max_length=127),
            preserve_default=False,
        ),
    ]
