# Generated by Django 2.0 on 2018-02-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
