# Generated by Django 2.0.3 on 2018-04-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_vacancy_allowed_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='contract_address',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='published',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='uuid',
            field=models.CharField(default='test uuid', max_length=64),
            preserve_default=False,
        ),
    ]
