# Generated by Django 2.0 on 2018-02-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_vacancy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
