# Generated by Django 2.0.3 on 2018-07-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
        ('vacancy', '0004_auto_20180614_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateOnVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.Candidate')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.Vacancy')),
            ],
        ),
        migrations.RemoveField(
            model_name='profileonvacancy',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profileonvacancy',
            name='vacancy',
        ),
        migrations.DeleteModel(
            name='ProfileOnVacancy',
        ),
        migrations.AlterUniqueTogether(
            name='candidateonvacancy',
            unique_together={('candidate', 'vacancy')},
        ),
    ]
