# Generated by Django 2.0.3 on 2018-04-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_auto_20180406_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
