# Generated by Django 2.0 on 2018-02-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_auto_20180209_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='allowed_amount',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='interview_fee',
        ),
    ]
