# Generated by Django 2.0.3 on 2018-04-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_vacancy_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='enabled',
            field=models.NullBooleanField(default=False),
        ),
    ]
