# Generated by Django 2.0.4 on 2018-07-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_auto_20180703_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='uuid',
            field=models.CharField(max_length=66),
        ),
    ]
