# Generated by Django 2.0.3 on 2018-05-24 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_verified'),
        ('vacancy', '0006_auto_20180406_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='employer',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='company.Company'),
            preserve_default=False,
        ),
    ]
