# Generated by Django 2.0.2 on 2018-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_auto_20180209_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='enabled',
            field=models.NullBooleanField(default=None),
        ),
    ]
