# Generated by Django 2.0.2 on 2018-03-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_auto_20180228_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('-updated_at',)},
        ),
    ]
