# Generated by Django 2.0.2 on 2018-03-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0029_auto_20180305_0603'),
        ('vacancy', '0009_vacancyoffer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancyoffer',
            unique_together={('vacancy', 'cv')},
        ),
    ]
