# Generated by Django 2.0.2 on 2018-03-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0010_auto_20180305_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyoffer',
            name='is_active',
            field=models.NullBooleanField(default=None),
        ),
    ]
