# Generated by Django 2.0.2 on 2018-03-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0012_auto_20180306_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
