# Generated by Django 2.0.2 on 2018-03-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0014_auto_20180312_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyoffer',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='cv.CurriculumVitae'),
        ),
    ]
