# Generated by Django 2.0.4 on 2018-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.CharField(blank=True, max_length=400, null=True)),
                ('raw2', models.CharField(blank=True, max_length=400, null=True)),
                ('address_line', models.CharField(blank=True, max_length=400, null=True)),
                ('city_state', models.CharField(blank=True, max_length=400, null=True)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='lat')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='lng')),
            ],
        ),
        migrations.CreateModel(
            name='AddressComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=400)),
                ('short_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AddressComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='addresscomponent',
            name='types',
            field=models.ManyToManyField(to='google_address.AddressComponentType'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_components',
            field=models.ManyToManyField(to='google_address.AddressComponent'),
        ),
    ]
