# Generated by Django 2.0.3 on 2018-05-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_address', '0005_auto_20170418_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleRegion',
        ),
    ]
