# Generated by Django 2.0.2 on 2018-03-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CvStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25)),
                ('obj_id', models.PositiveIntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cv_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25)),
                ('obj_id', models.PositiveIntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('vac_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
