# Generated by Django 2.0.3 on 2018-05-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CvStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25)),
                ('role_obj_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('obj_id', models.PositiveIntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('session_id', models.CharField(max_length=32)),
                ('count', models.PositiveIntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV statistic',
            },
        ),
        migrations.CreateModel(
            name='VacancyStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25)),
                ('role_obj_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('obj_id', models.PositiveIntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('session_id', models.CharField(max_length=32)),
                ('count', models.PositiveIntegerField(default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vacancy statistic',
            },
        ),
    ]
