# Generated by Django 2.0.2 on 2018-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvstatistic',
            options={'verbose_name': 'CV statistic'},
        ),
        migrations.AlterModelOptions(
            name='vacancystatistic',
            options={'verbose_name': 'Vacancy statistic'},
        ),
        migrations.RemoveField(
            model_name='cvstatistic',
            name='cv_id',
        ),
        migrations.RemoveField(
            model_name='vacancystatistic',
            name='vac_id',
        ),
        migrations.AddField(
            model_name='cvstatistic',
            name='role_obj_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancystatistic',
            name='role_obj_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
