# Generated by Django 2.0.2 on 2018-03-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20180321_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvstatistic',
            name='role_obj_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vacancystatistic',
            name='role_obj_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
