# Generated by Django 2.0.2 on 2018-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_auto_20180321_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvstatistic',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vacancystatistic',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
