# Generated by Django 2.0.2 on 2018-03-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_auto_20180321_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CvStatistic',
        ),
        migrations.DeleteModel(
            name='VacancyStatistic',
        ),
    ]
