# Generated by Django 2.0.2 on 2018-03-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0007_cvstatistic_vacancystatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvstatistic',
            name='elem_content_type',
        ),
        migrations.RemoveField(
            model_name='cvstatistic',
            name='role_content_type',
        ),
        migrations.RemoveField(
            model_name='vacancystatistic',
            name='elem_content_type',
        ),
        migrations.RemoveField(
            model_name='vacancystatistic',
            name='role_content_type',
        ),
        migrations.DeleteModel(
            name='CvStatistic',
        ),
        migrations.DeleteModel(
            name='VacancyStatistic',
        ),
    ]
