# Generated by Django 2.0.2 on 2018-03-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0009_cvstatistic_vacancystatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvstatistic',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacancystatistic',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
