# Generated by Django 2.0.4 on 2018-07-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('google_address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('published', models.BooleanField(default=False)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=512)),
                ('tax_number', models.CharField(max_length=64)),
                ('work_sector', models.CharField(max_length=512)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('legal_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_address.Address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='company.Company')),
            ],
        ),
    ]
