# Generated by Django 2.0.3 on 2018-05-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobboard', '0001_initial'),
        ('company', '0001_initial'),
        ('google_address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='jobboard.Employer'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_address.Address'),
        ),
    ]
