# Generated by Django 2.0.4 on 2018-08-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_company_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites',
                                              to='company.Company')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
