# Generated by Django 2.0.4 on 2018-08-01 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_requesttocompany'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requesttocompany',
            unique_together={('company', 'member')},
        ),
    ]
