# Generated by Django 2.0.3 on 2018-08-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0004_auto_20180801_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='legal_address',
            field=models.CharField(default='Klin', max_length=255),
            preserve_default=False,
        ),
    ]
