# Generated by Django 2.0.3 on 2018-04-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0002_auto_20180326_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'ordering': ('-created_at',)},
        ),
    ]
