# Generated by Django 2.0.3 on 2018-08-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobboard', '0002_auto_20180730_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='user',
            field=models.SmallIntegerField(default=0),
        ),
    ]
