# Generated by Django 2.0.3 on 2018-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobboard', '0003_auto_20180802_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='obj_id',
            field=models.CharField(max_length=127),
        ),
    ]
