# Generated by Django 2.0.3 on 2018-04-19 20:09

from django.db import migrations, models
import jobboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0004_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(default=jobboard.models.random_string, max_length=32, unique=True, verbose_name='code'),
        ),
    ]
