# Generated by Django 2.0 on 2018-01-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0006_auto_20180115_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_by_agreement',
        ),
    ]
