# Generated by Django 2.0.3 on 2018-05-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0006_invitecode_signup_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='organization',
        ),
        migrations.AddField(
            model_name='employer',
            name='first_name',
            field=models.CharField(default='Ivan', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='last_name',
            field=models.CharField(default='Ivanov', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
