# Generated by Django 2.0 on 2018-01-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0007_remove_vacancy_salary_by_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='interview_fee',
            field=models.CharField(default=0, max_length=31),
        ),
    ]
