# Generated by Django 2.0 on 2018-01-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0008_vacancy_interview_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='allowed_amount',
            field=models.CharField(default=0, max_length=31),
        ),
    ]
