# Generated by Django 2.0 on 2018-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0009_vacancy_allowed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumvitae',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
