# Generated by Django 2.0 on 2018-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0010_curriculumvitae_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumvitae',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
