# Generated by Django 2.0 on 2018-01-17 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0011_curriculumvitae_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.Vacancy')),
            ],
        ),
    ]
