# Generated by Django 2.0 on 2018-01-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0012_vacancytest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVacancyPassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.Candidate')),
            ],
        ),
        migrations.AddField(
            model_name='vacancytest',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidatevacancypassing',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.VacancyTest'),
        ),
    ]
