# Generated by Django 2.0 on 2018-01-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0013_auto_20180117_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancytest',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
