# Generated by Django 2.0 on 2018-01-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0015_candidatevacancypassing_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevacancypassing',
            name='passed',
            field=models.NullBooleanField(default=None),
        ),
    ]
