# Generated by Django 2.0 on 2018-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0018_auto_20180119_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='candidate',
            name='enabled',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='enabled',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='enabled',
            field=models.NullBooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
