# Generated by Django 2.0 on 2018-01-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0020_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='obj_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='retries',
            field=models.SmallIntegerField(default=0),
        ),
    ]
