# Generated by Django 2.0 on 2018-01-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0021_auto_20180119_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='retries',
        ),
    ]
