# Generated by Django 2.0 on 2018-01-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0022_remove_transaction_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vac_id',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
