# Generated by Django 2.0 on 2018-01-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0023_transaction_vac_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='snails',
            new_name='tax_number',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='inn',
            new_name='tax_number',
        ),
    ]
