# Generated by Django 2.0 on 2018-01-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0024_auto_20180124_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumvitae',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
