# Generated by Django 2.0 on 2018-01-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0025_curriculumvitae_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='specializations',
        ),
        migrations.DeleteModel(
            name='CurriculumVitae',
        ),
    ]
