# Generated by Django 2.0 on 2018-02-05 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0024_auto_20180205_0715'),
        ('jobboard', '0026_auto_20180130_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVOnVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.CurriculumVitae')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.Vacancy')),
            ],
        ),
    ]
