# Generated by Django 2.0 on 2018-02-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0028_transactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='action',
            field=models.CharField(max_length=512),
        ),
    ]
