# Generated by Django 2.0.2 on 2018-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0030_auto_20180208_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='enabled',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='employer',
            name='enabled',
            field=models.NullBooleanField(default=None),
        ),
    ]
