# Generated by Django 2.0.3 on 2018-05-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobboard', '0001_initial'),
        ('candidateprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='jobboard.Candidate'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.ManyToManyField(blank=True, to='candidateprofile.Education'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.ManyToManyField(blank=True, to='candidateprofile.Experience'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='jobboard.Keyword'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidateprofile.EducationLevel'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='specialisations',
            field=models.ManyToManyField(blank=True, to='jobboard.Specialisation'),
        ),
        migrations.AlterUniqueTogether(
            name='languageitem',
            unique_together={('language', 'resume')},
        ),
    ]
