# Generated by Django 2.0.3 on 2018-05-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateprofile', '0002_auto_20180528_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languageitem',
            old_name='resume',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='enabled',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='languageitem',
            name='level',
            field=models.CharField(choices=[('NOT', 'Notion'), ('BAS', 'Basic'), ('ADV', 'Advanced'), ('PRO', 'Professional'), ('BIL', 'Bilingual')], default='NOT', max_length=5, verbose_name='level'),
        ),
        migrations.AlterUniqueTogether(
            name='languageitem',
            unique_together={('language', 'profile')},
        ),
    ]
