# Generated by Django 2.0.3 on 2018-05-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateprofile', '0003_auto_20180531_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='description',
        ),
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='', max_length=5, unique=True, verbose_name='language code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.TextField(blank=True, max_length=2000, verbose_name='native name'),
        ),
    ]
