# Generated by Django 2.0.3 on 2018-05-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidateprofile', '0004_auto_20180531_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.AddField(
            model_name='citizenship',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidateprofile.Country'),
        ),
        migrations.AddField(
            model_name='citizenship',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizenship', to='candidateprofile.CandidateProfile'),
        ),
    ]
