# Generated by Django 2.0.3 on 2018-05-31 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidateprofile', '0005_auto_20180531_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidateprofile.Country')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_permit', to='candidateprofile.CandidateProfile')),
            ],
        ),
    ]
