# Generated by Django 2.0.3 on 2018-06-13 10:24

import candidateprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateprofile', '0006_workpermit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_month',
            field=models.IntegerField(blank=True, choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], null=True, verbose_name='end month'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_month',
            field=models.IntegerField(choices=[(1, 'january'), (2, 'february'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], default=candidateprofile.models.current_month, verbose_name='start month'),
        ),
    ]
