# Generated by Django 2.0.3 on 2018-06-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidateprofile', '0007_auto_20180613_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='published',
        ),
    ]
