# Generated by Django 2.0.3 on 2018-07-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
        ('candidateprofile', '0008_remove_candidateprofile_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='jobboard.Candidate')),
            ],
        ),
        migrations.RenameField(
            model_name='education',
            old_name='education_to',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='education_from',
            new_name='start',
        ),
    ]
