# Generated by Django 2.0.4 on 2018-07-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateprofile', '0009_auto_20180703_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='name'),
        ),
    ]
