# Generated by Django 2.0 on 2018-01-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busyness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('birth_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('city', models.CharField(max_length=127)),
                ('relocation', models.NullBooleanField(default=None)),
                ('official_journey', models.NullBooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=127, null=True)),
                ('faculty', models.CharField(blank=True, max_length=127, null=True)),
                ('profession', models.CharField(blank=True, max_length=127, null=True)),
                ('education_form', models.DateField()),
                ('education_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.EducationLevel')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expire', models.BooleanField(default=False)),
                ('organization', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=127)),
                ('position', models.CharField(max_length=127)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('NOT', 'Notion'), ('BAS', 'Basic'), ('ADV', 'Advanced'), ('PRO', 'Professional'), ('BIL', 'Bilingual')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('salary_from', models.PositiveIntegerField(default=0)),
                ('carier_start', models.BooleanField(default=False)),
                ('busyness', models.ManyToManyField(to='cv.Busyness')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='schedule',
            field=models.ManyToManyField(to='cv.Schedule'),
        ),
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.EducationLevel'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='education',
            field=models.ManyToManyField(to='cv.Education'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='experience',
            field=models.ManyToManyField(to='cv.Experience'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='languages',
            field=models.ManyToManyField(to='cv.Languages'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Position'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='skills',
            field=models.ManyToManyField(to='cv.Skill'),
        ),
    ]
