# Generated by Django 2.0.3 on 2018-03-23 11:24

import cv.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busyness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('city', models.CharField(max_length=127)),
                ('relocation', models.NullBooleanField(default=None)),
                ('official_journey', models.NullBooleanField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='jobboard.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=127, null=True)),
                ('faculty', models.CharField(blank=True, max_length=127, null=True)),
                ('profession', models.CharField(blank=True, max_length=127, null=True)),
                ('education_from', models.DateField()),
                ('education_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.EducationLevel')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(choices=[(2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950)], default=cv.models.current_year, verbose_name='start year')),
                ('start_month', models.IntegerField(choices=[(1, 'january'), (2, 'febuary'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], default=cv.models.current_month, verbose_name='start month')),
                ('still', models.BooleanField(default=False, verbose_name='still in office')),
                ('end_year', models.IntegerField(blank=True, choices=[(2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950)], null=True, verbose_name='end year')),
                ('end_month', models.IntegerField(blank=True, choices=[(1, 'january'), (2, 'febuary'), (3, 'march'), (4, 'april'), (5, 'may'), (6, 'june'), (7, 'july'), (8, 'august'), (9, 'september'), (10, 'october'), (11, 'november'), (12, 'december')], null=True, verbose_name='end month')),
                ('organization', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=127)),
                ('position', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('Notion', 'Notion'), ('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Professional', 'Professional'), ('Bilingual', 'Bilingual')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('salary_from', models.PositiveIntegerField(default=0)),
                ('carier_start', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('busyness', models.ManyToManyField(to='cv.Busyness')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='schedule',
            field=models.ManyToManyField(to='cv.Schedule'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='education',
            field=models.ManyToManyField(blank=True, to='cv.Education'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='experience',
            field=models.ManyToManyField(blank=True, to='cv.Experience'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='jobboard.Keyword'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='languages',
            field=models.ManyToManyField(blank=True, to='cv.Languages'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.EducationLevel'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv.Position'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='specialisations',
            field=models.ManyToManyField(blank=True, to='jobboard.Specialisation'),
        ),
    ]
