# Generated by Django 2.0.3 on 2018-03-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busyness',
            name='title',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='title',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=127),
        ),
    ]
