# Generated by Django 2.0.3 on 2018-04-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20180326_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumvitae',
            name='uuid',
            field=models.CharField(default='test uuid', max_length=64),
            preserve_default=False,
        ),
    ]
