# Generated by Django 2.0 on 2018-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_curriculumvitae_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumvitae',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
