# Generated by Django 2.0 on 2018-01-30 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_curriculumvitae_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumvitae',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
