# Generated by Django 2.0 on 2018-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_position_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
