# Generated by Django 2.0 on 2018-01-31 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20180131_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='education_form',
        ),
        migrations.AddField(
            model_name='education',
            name='education_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
