# Generated by Django 2.0 on 2018-01-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_auto_20180131_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
