# Generated by Django 2.0 on 2018-01-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_auto_20180131_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, to='cv.Education'),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='experience',
            field=models.ManyToManyField(blank=True, null=True, to='cv.Experience'),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='cv.Languages'),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='cv.Skill'),
        ),
    ]
