# Generated by Django 2.0 on 2018-02-01 06:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_auto_20180131_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
