# Generated by Django 2.0 on 2018-02-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
