# Generated by Django 2.0 on 2018-02-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_auto_20180131_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='busyness',
        ),
        migrations.RemoveField(
            model_name='position',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
