# Generated by Django 2.0 on 2018-02-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_auto_20180201_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('salary_from', models.PositiveIntegerField(default=0)),
                ('carier_start', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('busyness', models.ManyToManyField(to='cv.Busyness')),
                ('schedule', models.ManyToManyField(to='cv.Schedule')),
            ],
        ),
    ]
