# Generated by Django 2.0 on 2018-02-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_curriculumvitae_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='weight',
        ),
    ]
