# Generated by Django 2.0 on 2018-02-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0022_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='still',
            field=models.BooleanField(default=False, verbose_name='still in office'),
        ),
    ]
