# Generated by Django 2.0 on 2018-02-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0023_auto_20180201_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
