# Generated by Django 2.0 on 2018-02-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0027_cvonvacancy'),
        ('cv', '0024_auto_20180205_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='user',
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobboard.Candidate'),
            preserve_default=False,
        ),
    ]
