# Generated by Django 2.0 on 2018-02-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0025_auto_20180205_0816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
