# Generated by Django 2.0 on 2018-02-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0030_auto_20180208_0654'),
        ('cv', '0026_delete_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='skills',
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='jobboard.Keyword'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='specialisations',
            field=models.ManyToManyField(blank=True, to='jobboard.Specialisation'),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='education',
            field=models.ManyToManyField(blank=True, to='cv.Education'),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='experience',
            field=models.ManyToManyField(blank=True, to='cv.Experience'),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='languages',
            field=models.ManyToManyField(blank=True, to='cv.Languages'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
