# Generated by Django 2.0.2 on 2018-03-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0027_auto_20180208_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
