# Generated by Django 2.0.2 on 2018-03-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0028_cvreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculumvitae',
            old_name='specialisations',
            new_name='specializations',
        ),
    ]
