# Generated by Django 2.0.2 on 2018-03-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0029_auto_20180305_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculumvitae',
            old_name='specializations',
            new_name='specialisations',
        ),
    ]
