# Generated by Django 2.0.2 on 2018-03-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0030_auto_20180306_0542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CVReport',
        ),
    ]
