# Generated by Django 2.0.2 on 2018-03-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0031_delete_cvreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='jobboard.Candidate'),
        ),
    ]
